In [2]:
import cv2
import face_recognition
 
imgElon = face_recognition.load_image_file('ca.jpg')
imgElon = cv2.cvtColor(imgElon,cv2.COLOR_BGR2RGB)
imgTest = face_recognition.load_image_file('ca.jpg')
imgTest = cv2.cvtColor(imgTest,cv2.COLOR_BGR2RGB)
 
faceLoc = face_recognition.face_locations(imgElon)[0]
encodeElon = face_recognition.face_encodings(imgElon)[0]
cv2.rectangle(imgElon,(faceLoc[3],faceLoc[0]),(faceLoc[1],faceLoc[2]),(255,0,255),2)
 
faceLocTest = face_recognition.face_locations(imgTest)[0]
encodeTest = face_recognition.face_encodings(imgTest)[0]
cv2.rectangle(imgTest,(faceLocTest[3],faceLocTest[0]),(faceLocTest[1],faceLocTest[2]),(255,0,255),2)
 
results = face_recognition.compare_faces([encodeElon],encodeTest)
faceDis = face_recognition.face_distance([encodeElon],encodeTest)
print(results,faceDis)
cv2.putText(imgTest,f'{results} {round(faceDis[0],2)}',(50,50),cv2.FONT_HERSHEY_COMPLEX,1,(0,0,255),2)
 
cv2.imshow('Elon Musk',imgElon)
cv2.imshow('Elon Test',imgTest)
cv2.waitKey(0)
cv2.destroyAllWindows()

[True] [0.]


# CHECKING

In [4]:
import cv2
import csv
from datetime import datetime
import numpy as np
import face_recognition
import os
import pickle
def findEncodings(images):
    encodeList = []
    for img in images:
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        encode = face_recognition.face_encodings(img)[0]
        encodeList.append(encode)
    return encodeList


def markAttendance(name):
    with open('Attendance.csv', 'a', newline='') as f:
        csv_writer = csv.writer(f)

        # Read existing data to check if the name is already present
        nameList = []
        with open('Attendance.csv', 'r') as file:
            reader = csv.reader(file)
            for line in reader:
                # Check if the line is non-empty before accessing its elements
                if line:
                    entry = line[0].split(',')
                    if entry:
                        nameList.append(entry[0])

        # Check if the name is not already in the list, then add it
        if name not in nameList:
            now = datetime.now()
            dtString = now.strftime('%H:%M:%S')

            # Write the new attendance entry
            csv_writer.writerow([name, dtString])

path = 'ImageAtt'
images = []
classNames = []
myList = os.listdir(path)
print(myList)
for cl in myList:
    curImg = cv2.imread(f'{path}/{cl}')
    images.append(curImg)
    classNames.append(os.path.splitext(cl)[0])
print(classNames)

# Check if encoding file exists
encoding_file = 'encodings.pkl'
if os.path.exists(encoding_file):
    print("Loading Existing model")
    with open(encoding_file, 'rb') as f:
        encodeListKnown = pickle.load(f)
else:
    print("Training the model")
    encodeListKnown = findEncodings(images)
    with open(encoding_file, 'wb') as f:
        pickle.dump(encodeListKnown, f)

print('Model Loaded')

cap = cv2.VideoCapture(0)

while True:
    success, img = cap.read()
    imgS = cv2.resize(img, (0, 0), None, 0.25, 0.25)
    imgS = cv2.cvtColor(imgS, cv2.COLOR_BGR2RGB)

    facesCurFrame = face_recognition.face_locations(imgS)
    encodesCurFrame = face_recognition.face_encodings(imgS, facesCurFrame)

    for encodeFace, faceLoc in zip(encodesCurFrame, facesCurFrame):
        matches = face_recognition.compare_faces(encodeListKnown, encodeFace)
        faceDis = face_recognition.face_distance(encodeListKnown, encodeFace)
        print(faceDis)
        matchIndex = np.argmin(faceDis)

        if matches[matchIndex]:
            name = classNames[matchIndex].upper()
            print(name)
            y1, x2, y2, x1 = faceLoc
            y1, x2, y2, x1 = y1 * 4, x2 * 4, y2 * 4, x1 * 4
            cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)
            cv2.rectangle(img, (x1, y2 - 35), (x2, y2), (0, 255, 0), cv2.FILLED)
            cv2.putText(img, name, (x1 + 6, y2 - 6), cv2.FONT_HERSHEY_COMPLEX, 1, (255, 255, 255), 2)
            markAttendance(name)
    cv2.imshow('Webcam', img)
    if cv2.waitKey(1) == 13:  # 13 is the Enter Key
        break

cap.release()
cv2.destroyAllWindows()

['Ali.jpeg', 'andrew.jpg', 'chris.jpg', 'Elon.jpg']
['Ali', 'andrew', 'chris', 'Elon']
Training the model
Encoding Loaded
[0.43543141 0.7760561  0.83361727 0.79033679]
ALI
[0.43142634 0.75881373 0.80274314 0.78086566]
ALI
[0.43778701 0.7690337  0.78272515 0.79267031]
ALI
[0.44562942 0.80731589 0.77663641 0.78784394]
ALI


# Corrected 

In [4]:
import cv2
import csv
from datetime import datetime
import numpy as np
import face_recognition
import os
from datetime import datetime
# from PIL import ImageGrab
 
path = 'ImageAtt'
images = []
classNames = []
myList = os.listdir(path)
print(myList)
for cl in myList:
    curImg = cv2.imread(f'{path}/{cl}')
    images.append(curImg)
    classNames.append(os.path.splitext(cl)[0])
print(classNames)
def findEncodings(images):
    encodeList = []
    for img in images:
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        encode = face_recognition.face_encodings(img)[0]
        encodeList.append(encode)
    return encodeList


def markAttendance(name):
    with open('Attendance.csv', 'a', newline='') as f:
        csv_writer = csv.writer(f)

        # Read existing data to check if the name is already present
        nameList = []
        with open('Attendance.csv', 'r') as file:
            reader = csv.reader(file)
            for line in reader:
                # Check if the line is non-empty before accessing its elements
                if line:
                    entry = line[0].split(',')
                    if entry:
                        nameList.append(entry[0])

        # Check if the name is not already in the list, then add it
        if name not in nameList:
            now = datetime.now()
            dtString = now.strftime('%H:%M:%S')

            # Write the new attendance entry
            csv_writer.writerow([name, dtString])

# Example usage

encode=findEncodings(images)
print(len(encode))
encodeListKnown = findEncodings(images)
print('Encoding Complete')
 
cap = cv2.VideoCapture(0)
 
while True:
    success, img = cap.read()
    #img = captureScreen()
    imgS = cv2.resize(img,(0,0),None,0.25,0.25)
    imgS = cv2.cvtColor(imgS, cv2.COLOR_BGR2RGB)

    facesCurFrame = face_recognition.face_locations(imgS)
    encodesCurFrame = face_recognition.face_encodings(imgS,facesCurFrame)

    for encodeFace,faceLoc in zip(encodesCurFrame,facesCurFrame):
        matches = face_recognition.compare_faces(encodeListKnown,encodeFace)
        faceDis = face_recognition.face_distance(encodeListKnown,encodeFace)
        print(faceDis)
        matchIndex = np.argmin(faceDis)
 
        if matches[matchIndex]:
            name = classNames[matchIndex].upper()
            print(name)
            y1,x2,y2,x1 = faceLoc
            y1, x2, y2, x1 = y1*4,x2*4,y2*4,x1*4
            cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,0),2)
            cv2.rectangle(img,(x1,y2-35),(x2,y2),(0,255,0),cv2.FILLED)
            cv2.putText(img,name,(x1+6,y2-6),cv2.FONT_HERSHEY_COMPLEX,1,(255,255,255),2)
            markAttendance(name)
    cv2.imshow('Webcam',img)
    if cv2.waitKey(1) == 13: #13 is the Enter Key
        break
cap.release()
cv2.destroyAllWindows() 

['Ali.jpeg', 'andrew.jpg', 'chris.jpg', 'Elon.jpg']
['Ali', 'andrew', 'chris', 'Elon']
4
Encoding Complete
[0.46918512 0.77953692 0.79978154 0.79320404]
ALI
[0.43311643 0.78344979 0.80005959 0.78952484]
ALI
[0.45796474 0.80255656 0.8452558  0.82363944]
ALI
[0.4524844  0.79228131 0.81537026 0.81486123]
ALI
[0.43201496 0.78321053 0.79896192 0.8086454 ]
ALI
[0.43069094 0.82583003 0.82136249 0.83888472]
ALI
[0.42504399 0.81310079 0.83670538 0.85856555]
ALI
[0.4601598  0.79999905 0.80254332 0.82893453]
ALI
[0.45934105 0.82725584 0.81742067 0.83854281]
ALI
[0.44909316 0.80396585 0.78655604 0.81423302]
ALI
[0.48317992 0.82999724 0.78957044 0.85431178]
ALI
[0.4729299  0.80313733 0.77099091 0.8127182 ]
ALI
[0.46376362 0.77394566 0.76244899 0.76536872]
ALI
[0.50508946 0.74109476 0.75103603 0.77288035]
ALI
[0.45439264 0.78611012 0.74664028 0.79450491]
ALI
[0.45590429 0.76824412 0.77545784 0.80558843]
ALI
[0.49862078 0.77975417 0.76107754 0.76065947]
ALI
[0.47227419 0.75084056 0.74439629 0.8114948

In [ ]:
import cv2
import numpy as np
import face_recognition
import os
from datetime import datetime
# from PIL import ImageGrab
 
path = 'ImagesAttendance'
images = []
classNames = []
myList = os.listdir(path)
print(myList)
for cl in myList:
curImg = cv2.imread(f'{path}/{cl}')
images.append(curImg)
classNames.append(os.path.splitext(cl)[0])
print(classNames)
 
def findEncodings(images):
    encodeList = []
    for img in images:
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    encode = face_recognition.face_encodings(img)[0]
    encodeList.append(encode)
    return encodeList
 
def markAttendance(name):
    with open('Attendance.csv','r+') as f:
        myDataList = f.readlines()
        nameList = []
        for line in myDataList:
            entry = line.split(',')
            nameList.append(entry[0])
            if name not in nameList:
            now = datetime.now()
            dtString = now.strftime('%H:%M:%S')
            f.writelines(f'n{name},{dtString}')
 
#### FOR CAPTURING SCREEN RATHER THAN WEBCAM
# def captureScreen(bbox=(300,300,690+300,530+300)):
#     capScr = np.array(ImageGrab.grab(bbox))
#     capScr = cv2.cvtColor(capScr, cv2.COLOR_RGB2BGR)
#     return capScr
 
encodeListKnown = findEncodings(images)
print('Encoding Complete')
 
cap = cv2.VideoCapture(0)
 
while True:
    success, img = cap.read()
    #img = captureScreen()
    imgS = cv2.resize(img,(0,0),None,0.25,0.25)
    imgS = cv2.cvtColor(imgS, cv2.COLOR_BGR2RGB)

    facesCurFrame = face_recognition.face_locations(imgS)
    encodesCurFrame = face_recognition.face_encodings(imgS,facesCurFrame)

    for encodeFace,faceLoc in zip(encodesCurFrame,facesCurFrame):
    matches = face_recognition.compare_faces(encodeListKnown,encodeFace)
    faceDis = face_recognition.face_distance(encodeListKnown,encodeFace)
    print(faceDis)


In [ ]:
matchIndex = np.argmin(faceDis)
 
if matches[matchIndex]:
name = classNames[matchIndex].upper()
#print(name)
y1,x2,y2,x1 = faceLoc
y1, x2, y2, x1 = y1*4,x2*4,y2*4,x1*4
cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,0),2)
cv2.rectangle(img,(x1,y2-35),(x2,y2),(0,255,0),cv2.FILLED)
cv2.putText(img,name,(x1+6,y2-6),cv2.FONT_HERSHEY_COMPLEX,1,(255,255,255),2)
markAttendance(name)
 
cv2.imshow('Webcam',img)
cv2.waitKey(1)

In [ ]:
if matches[matchIndex]:
    name = classNames[matchIndex].upper()
    #print(name)
    y1,x2,y2,x1 = faceLoc
    y1, x2, y2, x1 = y1*4,x2*4,y2*4,x1*4
    cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,0),2)
    cv2.rectangle(img,(x1,y2-35),(x2,y2),(0,255,0),cv2.FILLED)
    cv2.putText(img,name,(x1+6,y2-6),cv2.FONT_HERSHEY_COMPLEX,1,(255,255,255),2)
    markAttendance(name)
#To find the unknown faces we will replace

#with this

if faceDis[matchIndex]< 0.50:
    name = classNames[matchIndex].upper()
    markAttendance(name)
else: name = 'Unknown'
#print(name)
y1,x2,y2,x1 = faceLoc
y1, x2, y2, x1 = y1*4,x2*4,y2*4,x1*4
cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,0),2)
cv2.rectangle(img,(x1,y2-35),(x2,y2),(0,255,0),cv2.FILLED)
cv2.putText(img,name,(x1+6,y2-6),cv2.FONT_HERSHEY_COMPLEX,1,(255,255,255),2)

# SNAP

Image saved: imgatt\captured_image.jpg


Face detected! Do you want to capture the image? (Y/N): y
Image saved: imgatt\captured_image.jpg


# Snapping Finalization

In [1]:
import cv2
import os

# Create a folder if it doesn't exist
output_folder = 'imgatt'
os.makedirs(output_folder, exist_ok=True)

# Load the pre-trained Haar Cascade Classifier for face detection
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

# Initialize the camera
cap = cv2.VideoCapture(0)

while True:
    # Capture frame-by-frame
    ret, frame = cap.read()
    img=frame.copy()

    # Convert the frame to grayscale for face detection
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Detect faces in the frame
    faces = face_cascade.detectMultiScale(gray, scaleFactor=1.3, minNeighbors=5)

    # Draw rectangles around the faces
    for (x, y, w, h) in faces:
        cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 2)
        cv2.putText(img, 'Face Detected Press Y to take picture', (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (255, 0, 0), 2, cv2.LINE_AA)
        print('Face Detected Press Y to take picture')
    # Display the frame
    if len(faces) == 0:
        cv2.putText(img, 'No Face Detected Press q to quit', (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 0, 255), 2, cv2.LINE_AA)
        print('No Face Detected Press q to quit')
    cv2.imshow('Face Detection', img)
#     if cv2.waitKey(1) & 0xFF == ord('Y') :
    key = cv2.waitKey(1) & 0xFF
    if key == ord('Y') or key == ord('y'):
        img_name = os.path.join(output_folder, 'captured_image.jpg')
        cv2.imwrite(img_name, frame)
        print(f"Image saved: {img_name}")
        break
    elif cv2.waitKey(1) & 0xFF == ord('q'):
        break
        

cap.release()
cv2.destroyAllWindows()


No Face Detected Press q to quit
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Pre

In [3]:
import cv2
import os

# Create a folder if it doesn't exist
output_folder = 'imgatt'
os.makedirs(output_folder, exist_ok=True)

# Load the pre-trained Haar Cascade Classifier for face detection
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

# Initialize the camera
cap = cv2.VideoCapture(0)

while True:
    # Capture frame-by-frame
    ret, frame = cap.read()
    img = frame.copy()
    # Convert the frame to grayscale for face detection
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Detect faces in the frame
    faces = face_cascade.detectMultiScale(gray, scaleFactor=1.3, minNeighbors=5)

    # Draw rectangles around the faces
    for (x, y, w, h) in faces:
        cv2.rectangle(img, (x, y), (x + w, y + h), (255, 0, 0), 2)
        cv2.putText(img, 'Face Detected Press Y to take picture', (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (255, 0, 0),
                    2, cv2.LINE_AA)
        print('Face Detected Press Y to take picture')
    # Display the frame
    if len(faces) == 0:
        cv2.putText(img, 'No Face Detected Press q to quit', (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 0, 255), 2,
                    cv2.LINE_AA)
        print('No Face Detected Press q to quit')
    cv2.imshow('Face Detection', img)

    key = cv2.waitKey(1) & 0xFF
    if key == ord('Y') or key == ord('y'):
        # Prompt user for the name of the person
        person_name = input("Enter the name of the person: ")

        # Save the image with the entered name
        img_name = os.path.join(output_folder, f'{person_name}.jpg')
        cv2.imwrite(img_name, frame)
        print(f"Image saved: {img_name}")
        break
    elif key == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detected Press Y to take picture
Face Detecte

In [5]:
import os

def delete_file_if_exists(folder_path, file_name):
    file_path = os.path.join(folder_path, file_name)

    if os.path.exists(file_path):
        os.remove(file_path)
        print(f"File '{file_name}' has been deleted.")
    else:
        print(f"File '{file_name}' is not present in the folder.")

def main():
    folder_path = "E:/RoboProj/ImageAtt"  # Replace with the actual path to your folder

    while True:
        file_name = input("Enter the name of the file (or 'exit' to quit): ")

        if file_name.lower() == 'exit':
            break

        delete_file_if_exists(folder_path, file_name)

if __name__ == "__main__":
    main()


Enter the name of the file (or 'exit' to quit): Lasd
File 'Lasd' is not present in the folder.
Enter the name of the file (or 'exit' to quit): Ali
File 'Ali' is not present in the folder.
Enter the name of the file (or 'exit' to quit): Ali.jpg
File 'Ali.jpg' has been deleted.
Enter the name of the file (or 'exit' to quit): exit


In [8]:
import os

def delete_file_if_exists(folder_path, file_name):
    for file in os.listdir(folder_path):
        if file_name == os.path.splitext(file)[0]:
            file_path = os.path.join(folder_path, file)

            if os.path.exists(file_path):
                os.remove(file_path)
                print(f"File '{file}' has been deleted.")
                return True

    print(f"File '{file_name}' is not present in the folder.")
    return False

def main():
    folder_path = "E:/RoboProj/ImageAtt"+{file_name}+".jpg" # Replace with the actual path to your folder

    while True:
        file_name = input("Enter the name of the file (or 'exit' to quit): ")

        if file_name.lower() == 'exit':
            break

        delete_file_if_exists(folder_path, file_name)

if __name__ == "__main__":
    main()


UnboundLocalError: local variable 'file_name' referenced before assignment

In [9]:
import os

def delete_file_if_exists(folder_path, file_name):
    for file in os.listdir(folder_path):
        base_name, extension = os.path.splitext(file)
        if file_name == base_name:
            file_path = os.path.join(folder_path, file)

            if os.path.exists(file_path):
                os.remove(file_path)
                print(f"File '{file}' has been deleted.")
                return True

    print(f"File '{file_name}' is not present in the folder.")
    return False

def main():
    folder_path = "E:/RoboProj/ImageAtt"  # Replace with the actual path to your folder

    while True:
        file_name = input("Enter the name of the file (or 'exit' to quit): ")

        if file_name.lower() == 'exit':
            break

        delete_file_if_exists(folder_path, file_name)

if __name__ == "__main__":
    main()


Enter the name of the file (or 'exit' to quit): chris
File 'chris.jpg' has been deleted.
Enter the name of the file (or 'exit' to quit): exit
